version: '2'
services:
  mysql:
    image: mysql
    container_name: ambition-mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ambition
      MYSQL_DATABASE: ambition
      MYSQL_USER: ambition
      MYSQL_PASSWORD: ambition
    volumes:
      - ./mysql/build_database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
      - ./mysql/database:/var/lib/mysql
  ambition:
    build: ./ambition-model
    depends_on:
      - mysql
