version: '2'
services:
  ambition-mysql:
    image: mysql:latest
    container_name: ambition-mysql-container
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ambition
      MYSQL_DATABASE: ambition
      MYSQL_USER: ambition
      MYSQL_PASSWORD: ambition
    volumes:
      - ./mysql/build_database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 
      - ./mysql/database:/var/lib/mysql
  ambition-model:
    build: ./ambition-model
    restart: always
    image: adamryman/ambition-model
    container_name: ambition-model-container
    environment:
      MYSQL_ROOT_PASSWORD: ambition
      MYSQL_DATABASE: ambition
      MYSQL_USER: ambition
      MYSQL_PASSWORD: ambition
      MYSQL_HOST: ambition-mysql
      MYSQL_PORT: 3306
      PORT: 55440
      HTTPPORT: 55439
    expose:
      - "55440"
      - "55439"
    ports:
      - "55440:55440"
      - "55439:55439"
    depends_on:
      - ambition-mysql
  rello:
    build: ./rello
    restart: always
    image: adamryman/rello
    container_name: ambition-rello
    expose:
      - "5040"
    ports:
      - "5040:5040"
    environment:
      ambition_grpc: ambition-model:55440
    depends_on:
      - ambition-model
