version: "2"
services:
  model:
    extends:
      file: docker-compose.common.yml
      service: model
    image: adamryman/fsrestarter
    ports:
      - ${MODEL_PORT_EXTERNAL}:${MODEL_PORT}
    volumes:
      - "$GOPATH/src/github.com/adamryman/ambition-model/target:/target"
  users:
    image: adamryman/fsrestarter
    ports:
      - ${USERS_PORT_EXTERNAL}:${USERS_PORT}
    volumes:
      - "$GOPATH/src/github.com/adamryman/ambition-users/target:/target"
  rello:
    image: adamryman/fsrestarter
    ports:
      - ${RELLO_PORT_EXTERNAL}:${RELLO_PORT}
    volumes:
      - "$GOPATH/src/github.com/adamryman/ambition-rello/target:/target"
